### PR TITLE
Updates to match Sphinx 1.6 interface changes, take 2

### LINKED ISSUE #29: Incompatibility with Sphinx 1.4.4+
### Summary of Problem
See https://github.com/chapel-lang/chapel/issues/5190

Sphinx has undergone a change since this domain was originally developed, so it is incompatible with version 1.4.4 and on.

Since most, if not all, uses of this domain are through chpldoc and the virtual environment in which it is built (which pins us to a specific Sphinx version), we view this as a low priority issue and so have not prioritized a fix for it yet

### LINKED ISSUE #5190: sphinxcontrib-chapeldomain not compatible with Sphinx 1.4.4+
### Summary of Problem

When building Chapel's docs outside of the venv with Sphinx 1.4.4+ (1.5.1 in my case), there are 3538 warnings. These warnings are caused by a change in Sphinx, described in the comments of: sphinx-doc/sphinx#2673

When we decide to upgrade our virtual-env's version of Sphinx and want to support the latest version (rather than pre-1.4.4 versions), we will need to update [sphinxcontrib-chapeldomain](https://github.com/chapel-lang/sphinxcontrib-chapeldomain) to support the new index structure.

Until then, this is a non-issue for both users and developers, since docs are always built inside of the virtual-environment.

### PR DESCRIPTION
**Pull request by mppf**
Replaces #30. This PR is a rebased version of that PR by @ben-albrecht that includes a single further change to enable `make docs` to function with newer sphinx.

Sphinx made some breaking changes between 1.2 and 1.6. This PR fixes
them for chapeldomain extension. 

Interface changes that were adjusted:

- `make_field` now requires an env argument (ignored by our implementation)
- `sphinx.util.compat.Directive` deprecated for `docutils.parsers.rst.Directive`
- `indexnode` is now a 5-element tuple instead of 4

Besides these changes, it moves from `chapeldomain.py` to `chapeldomain/__init__.py` since this matches the expected format for a subpackage in a namespace-only package.

## Testing
- [x] Builds Chapel's documentation
- [x] Passes nosetests
- [x] Passes docs tests
  
Closes #29
Closes https://github.com/chapel-lang/chapel/issues/5190

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Do you think we should aim for the latest version, Sphinx 2.20 or is it worthwhile to pursue 1.6 as an incremental step towards 2.2?

**Comment by mppf** [comment]
@ben-albrecht - Sphinx is Python 3 only starting with version 2. While we might go python-3 only on our docs build, I don't think that should be connected to the present effort.

```
# Sphinx==1.3.3 seems to work
# Sphinx==1.4.0 seems to work
# Sphinx==1.6.7 working as of d66b45746ea06ad06ec0d985540d382eaaacb0a1
# Sphinx==1.7 working
Sphinx==1.8.5
# Sphinx==2.0.1 # requires python 3
# Sphinx==2.1.2 # requires python 3
# Sphinx==2.2.0 # requires python 3
```

**Comment by cassella** [comment]
Does this resolve chapel-lang/chapel#5190 ?

**Comment by mppf** [comment]
The travis tests are failing due to some Python namespace issues. I think they can be solved by setting PYTHONPATH to the current directory (and possibly alternatively with `pip uninstall sphinxcontrib-websupport`). However, we are thinking of moving this to a different repo, which would avoid the issue as well.

**Review by ben-albrecht — APPROVED** [review]

**Pull request merged**
