### PR TITLE
Update to require Python 3

### PR DESCRIPTION
**Pull request by lydia-duncan**
We want to drop support for Python 2 and start taking advantage of later features
of Sphinx, or at the very least not be unreasonably far behind on Sphinx.

Update our Sphinx version from 1.8.5 to 3.2.1.  We've been on 1.8.5 for a while,
in part due to not being ready to switch to Python 3 full time.  Now that we want
to start relying on Python 3, update the version of Sphinx we use.

As part of this change, replace uses of `sphinx.locale.l_` with `sphinx.locale._`.
`l_` was deprecated and ultimately removed.  The deprecation message says to use
`_` instead, so do that.

Updates Travis to use 3.6 to test instead of 2.7 and 3.4.  Also updates setup.py and
the release script to use Python 3 as well, and for the new updates to the installation
requirements.  Everything should be tested except for the release script, which I was
worried would prematurely tag the release.

This change additionally migrates to using `python3 -m pip` instead of `pip` to
install packages, since pip is included in later python releases.  These changes were
originally performed by Michael on the main Chapel repo copy of this repository.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Things I need to do:
- [x]  ensure our testing machines can handle this.  Sphinx 3.2.1 (and everything after the version of Sphinx we were already using) requires Python 3.5 or higher but not all our machines have that
- [ ] ensure the Jenkins job we have to test this will work (it looks like it relies on Python 2 atm, need to update that)
- [x] maybe there are more scripts to update in this repo?
- [x] how do I test this locally again?  The Travis job doesn't seem to run all the tests I would expect

**Comment by lydia-duncan** [comment]
I opened Cray/chapel-private#1402 to talk about our testing machines and the version of Python we should use

**Comment by lydia-duncan** [comment]
I opened a PR in our private Jenkins configuration repo to adjust the Sphinx domain job.

**Comment by lydia-duncan** [comment]
I ran the nosetests that the Jenkins job runs and they all passed, so I think this works?

**Comment by lydia-duncan** [comment]
The "X" is because Travis now automatically cancels jobs when it notices you have a new commit, sadly.

**Review by mppf — APPROVED** [review]
Please:
 * remove the version numbers from setup.py (rely on requirements.txt for this)
 * double-check we have no other mods to this in the copy in the chapel repo

**Pull request merged**
